### ISSUE TITLE
Boot Module setting not retained

### ISSUE THREAD

**Issue by stalinCCCP415** [IsThisMeta/zagreus#206]
The app doesn't retain the setting for "Boot Module" after quitting and reopening the app. It always go back to Dashboard. 

iOS 26.1
App Version 11.8.0

**Comment by IsThisMeta** [comment]
Resolved in 2.0

**Comment by toyanucci** [comment]
I’m on version 12.0.3 and still having this issue. 

iPhone 17 Pro Max
App version 12.0.3
iOS 26.3

**Comment by toyanucci** [comment]
Thank you!
